__author__ = 'wang'

fileExtensionDict = {'dcm': 'dicom',
                     'dcm.gz': 'dicom',
                     'nii': 'nifti',
                     'nii.gz': 'nifti',
                     'mnc': 'minc',
                     'mnc.gz': 'minc',
                     'v': 'v'}

fileExtensionTuple = ('.nii', '.dcm', '.mnc', '.nii.gz', '.dcm.gz', '.mnc.gz', '.v', '.v.gz')

scanTypeDict = {'4x5minute_frames_4i_16s__AV45': 'AV45',
                '4x5minute_frames_-_Iter_Bra_AV45': 'AV45',
                '50-70_min_dynamic-3D_4i_16s_AV45': 'AV45',
                'ADNI2_AV45__AC_': 'AV45',
                'ADNI_BRAIN_3D__AV45': 'AV45',
                'ADNI_Brain_PET__Raw_AV45': 'AV45',
                'ADNIGO_-_AV45_BRAIN_STUDY': 'AV45',
                'ADNI_GO_PRIMARY__AV45': 'AV45',
                'ASL_PERFUSION': 'ASL_P',
                'AV45_Dyn_4x5min_2Di_336_2z_AllPass__AC_': 'AV45',
                'Average_DC': 'Ave_DC',
                'Axial_DTI': 'A_DTI',
                'Dyn_ADNI-GO_128x,4i20s,256mmFOV,NoFilter___AV45': 'AV45',
                'Enhanced_Axial_DTI': 'EA_DTI',
                'Extended_Resting_State_fMRI': 'ext-rsfmri',
                'Fractional_Aniso.': 'F_Aniso',
                'Isotropic_image': 'I_image',
                'MoCoSeries': 'MoCo',
                'MPR__GradWarp': 'MPR',
                'MPR__GradWarp__B1_Correction': 'MPR_B1',
                'MPR__GradWarp__B1_Correction__Mask': 'MPR_B1_M',
                'MPR-R__GradWarp': 'MPR-R',
                'MPR-R__GradWarp__B1_Correction': 'MPR-R_B1',
                'MPR-R__GradWarp__B1_Correction__Mask': 'MPR-R_B1_M',
                'MT1__GradWarp__N3m': 'MT1_G_N3m',
                'MT1__N3m': 'MT1_N3m',
                'Perfusion_Weighted': 'Perf_W',
                'PET_AC_3D_BRAIN__AV45': 'AV45',
                'PET_Brain_AV_45__AV45': 'AV45',
                'PET_Brain_COR_ADNI_#2__AC__AV45': 'AV45',
                'relCBF': 'relCBF',
                'Spatially_Normalized,_Masked_and_N3_corrected_T1_image': '3TT1-SNMN3C',
                'PET_Brain__AV45': 'AV45',
                '3D_ADNI2_AV45_F18_ACQUI._4i_16s': 'AV45',
                'ADNI2_FDG__AC_': 'FDG',
                '30_min_3D_FDG_4i_16s': 'FDG',
                '[F-18]_20_min_4i_16s__AV45': 'AV45'}

